### ISSUE TITLE
Create plan for Shiny app

### ISSUE THREAD

**Issue by f-hafner** [Dynamo-HIA/hiaR#10]
#### Reduce the number of tabs to 2
- "configuration" -> combine program configuration and simulation configuration
- the rest (good name?): risk factors, diseases, relative risks, scenarios
	- -> this is similar to the old GUI
	- note: the user may add multiple scenarios, which can make the page long -> we have different options here
		- put the scenarios at the bottom
			- either allow to expand/un-expand to make the page shorter
		- put them on a separate tab

#### show help in a popover/tooltip
- the old GUI had descriptions about what the different user inputs mean/what they should do 
- we can try to do something similar, for instanct with `bslib`, that has tooltips and popovers. https://shiny.posit.co/blog/posts/bslib-tooltips/. we need to check if they match our requirements. there is also an alternative in the [`shinyBS` package](https://www.rdocumentation.org/packages/shinyBS/versions/0.61.1/topics/Tooltips_and_Popovers), but it seems less popular on github. 

#### simplify the display of the `Diseases` inputs
for instance, only show the following column when the user selects this Disease in the checkbox
![image](https://github.com/user-attachments/assets/792f4402-af52-4b5a-8e15-bbb928de89b5)

such logic could be implemented in different ways. 

for instance, with an accordion
- https://rstudio.github.io/bslib/reference/accordion.html
- non-R example here: https://getbootstrap.com/docs/5.3/components/accordion/

or with contingent display in shinyjs? https://debruine.github.io/shinyintro/contingency.html

**Comment by f-hafner** [comment]
in addition
- the gui should dynamically show only files that exist in the reference data. For instance, if `Odds_Ratio_For_Disability` in a risk factor is missing, it should not appear in the GUI.

**Comment by maltelueken** [comment]
This seems to be outdated.
