### ISSUE TITLE
Shiny GUI: smaller ideas and open questions

### ISSUE THREAD

**Issue by f-hafner** [Dynamo-HIA/hiaR#9]
I went through the shiny gui on main, the directory structure, and partly through the old GUI. here are some smaller/vaguer ideas and some open questions about the difference between the old gui and the current gui on main

- in `Scenarios`
	- should there be an option to select gender?
	- replace the min and max age with a slider? - this is a matter of taste, but this would probably allow to put constraints on the possible values
- in `Relative Risks`
	- display the option is some visually appealing way, for instance by having "from" and "to" diseases in boxes, and allowing the user to connect boxes one disease with another, and then being able to select the relevant reference data files. 
	- are all transition probabilities captured? the app shows 11 options, but there seem to be 52 files. the R code does some `summarize` in the `shiny_app.R`, so this may all be fine.
```bash
      cd Reference_Data
      find ./ -name "RR_*" | wc -l 
      # 52
```

- in `Risk Factors`: add more options? see pictures from the old GUI:

![gui1_small](https://github.com/user-attachments/assets/ecc6ca99-b1c7-4461-9dd4-001563288b26)

![gui2_small](https://github.com/user-attachments/assets/b7d8586f-87d7-4fa6-a9b0-9174e37980f8)

**Comment by maltelueken** [comment]
This seems to be outdated.
